learning_templates/basic_app/urls.py
from django.urls import path
from basic_app import views

# TEMPLATE TAGGING
app_name = 'basic_app'

urlpatterns = [
    path('relative/', views.relative, name='relative'),
    path('other/', views.other, name='other'),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('basic_app/', include('basic_app.urls')),
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    context_dict = {'text': 'hello world', 'number': 100}
    return render(request, 'basic_app/index.html', context=context_dict)


def other(request):
    return render(request, 'basic_app/other.html')


def relative(request):
    return render(request, 'basic_app/relative_url_templates.html')

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <meta charset="UTF-8" />
        <title></title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    </head>
    <body>
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <ul class="nav navbar-nav">
                    <li><a class="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
                    <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                    <li><a class="navbar-link" href="{% url 'basic_app:other' %}">Other</a></li>
                </ul>
            </div>
        </nav>
        <div class="container">
            {% block body_block %}
            {% comment %} Anything outside of here will be inherited if you extend! {% endcomment %}
            {% endblock %}
        </div>
    </body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% load my_custome_filter %}
    {% block body_block %}
        <h1> Welcome to Index!</h1>
        <h1> This is index.html page showing!</h1>
        {{ text|cut_filter:"world"}}
        {{ number|add:"99" }}
    {% endblock  %}
                
              

learning_templates/templates/basic_app/other.html
<!DOCTYPE html> {% comment %}this is always at top of each html file {% endcomment %}
{% extends "basic_app/base.html" %} {% comment %} extends brings everything outside of body_block tag here {% endcomment %}
    {% block body_block %}
        <h1> Welcome to Other!</h1>
        <h2> This is an example of template inheritance!</h2>
    {% endblock %}
            

learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <meta charset="UTF-8" />
        <title>HOME</title>
        {% comment %} <link rel="stylesheet" href='{% static "css/mystyle.css" %}' /> {% endcomment %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    </head>
    <body>
        <div class="container">
            <div class="jumbotron">
                <h1> Welcome to Relative URL Templates!</h1>
                {% comment %} <h2>Go to /formpage to fill out the form</h2> {% endcomment %}
                <a href="{% url 'basic_app:other' %}">LINK TO OTHER PAGE</a>
                <a href="{% url 'admin:index' %}">LINK TO ADMIN</a>
                <a href="{% url 'index' %}">LINK TO INDEX</a>
            </div>
        </div>
    </body>
</html>