class_based_view/advcbv/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('classview/', views.CBView.as_view()),
    path('', views.IndexView.as_view()),
    path('basic_app/', include('basic_app.urls', namespace='basic_app'))
]

class_based_view/basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    path('', views.SchoolListView.as_view(), name="list"),
    path('<int:pk>/', views.SchoolDetailView.as_view(), name="detail"),
    path('create/', views.SchoolCreateView.as_view(), name="create"),
    path('update/<int:pk>/', views.SchoolUpdateView.as_view(), name="update"),
    path('delete/<int:pk>/', views.SchoolDeleteView.as_view(), name="delete")
]

class_based_view/basic_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class School (models.Model):

    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('basic_app:detail', kwargs={'pk': self.pk})


class Student (models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(
        School, related_name='students',
        on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name

class_based_view/basic_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import (View, TemplateView, ListView, DetailView,
                                  CreateView, UpdateView, DeleteView)
from . import models

# Create your views here.


class CBView(View):
    '''it is a very basic class based view
       we don't appreciate how useful CBV is until we use
       generic Template Based View
    '''

    def get(self, request):
        return HttpResponse("Class Based Views are cool!")


class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["injectme"] = "Basic Injection"
        context["school_count"] = models.School.objects.all().count()
        context["student_count"] = models.Student.objects.all().count()
        return context


class SchoolListView(ListView):
    # context_object_name = 'schools'
    # as context, 'school_list' & 'object_list' is getting returened automatically by ListView
    # however we cab changed the context name to be something else e.g. 'schools'
    model = models.School
    # school_list


class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    # as context, 'school', & 'object' is getting returened automatically by DetailView
    # however we changed the context name to be 'school_detail'
    model = models.School
    # template_name = "basic_app/school_detail.html"


class SchoolCreateView(CreateView):
    model = models.School
    fields = ('name', 'principal', 'location')


class SchoolUpdateView(UpdateView):
    model = models.School
    fields = ('name', 'principal')


class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy('basic_app:list')

class_based_view/basic_app/templates/basic_app/school_confirm_delete.html
{% extends 'base.html' %}
{% block body_block %}
<div class='container'>
    <h1>You are deleting the school: {{school.name}}</h1>
    <h1>Are you sure about it?</h1>
    <form method='post'>
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'basic_app:detail' pk=school.pk %}">Cancel</a>
    </form>
    
<div>

{% endblock %}

class_based_view/basic_app/templates/basic_app/school_detail.html
{% extends 'base.html' %}
{% block body_block %}
<div class='jumbotron'>
    <h1>Welcome to School Detail Page</h1>
    <h2>School Details:</h2>
    <p>Name: {{school_detail.name}}</p>
    <p>Name: {{object.name}}</p>
    <p>Principal: {{school_detail.principal}}</p>
    <p>Location: {{school_detail.location}}</p>
    <h3>Students:</h3>
    {% for student in school_detail.students.all %}
        <p> {{student.name}} who is {{student.age}} years old.</p>
    {% endfor %}
</div>
<div>
    <a href="{% url 'basic_app:update' pk=school_detail.pk  %}" class='btn btn-warning'>Update</a>
    <a href="{% url 'basic_app:delete' pk=school_detail.pk  %}" class='btn btn-danger'>Delete</a>
</div>
{% endblock %}

class_based_view/basic_app/templates/basic_app/school_form.html
{% extends 'base.html' %}
{% block body_block %}
<h1>
    {% if not form.instance.pk  %}
        Create School
    {% else %}
        Update School
    {% endif %}
</h1>

<form method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary" value="Submit"></input>
</form>
{% endblock %}

class_based_view/basic_app/templates/basic_app/school_list.html
{% extends 'base.html' %}
{% block body_block %}

<h1>Welcome to a list of all the schools!</h1>

<ol>
    {% for school in school_list %}
        <h2><li><a href="{{school.id}}">{{school.name}}</a></li></h2>
    {% endfor %}
    {% comment %} {% for school in object_list %}
        <h2><li><a href="{{school.id}}">{{school.name}}</a></li></h2>
    {% endfor %} {% endcomment %}
</ol>

{% endblock %}

class_based_view/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
          <ul class="nav navbar-nav">
              <li><a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</a></li>
              <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>

          </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
        <h1>Hello from Base!</h1>
      {% endblock %}
    </div>
  </body>
</html>

class_based_view/templates/index.html
{% extends 'base.html' %}
{% block body_block %}
<div class="jumbotron">
  <h1>Home Pgae!</h1>
  <h2>Injected Content: {{ injectme }}</h2>
  <h3>Number of Schools: {{ school_count }}</h3>
  <h3>Number of Students: {{ student_count }}</h3>
</div>
{% endblock %}